import Modal from "@/components/Modal";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Trello 2.0 clone",
  description: "Generated by loucarass",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-Br">
      <body className="bg-[#f5f6f8]">
        {children}
        <Modal/>
        </body>
    </html>
  );
}
